In [2]:
import pandas as pd

In [43]:
races = pd.read_csv('races.csv')
results = pd.read_csv('results.csv')
drivers = pd.read_csv('drivers.csv')
constructors = pd.read_csv('constructors.csv')
driver_standings = pd.read_csv('driver_standings.csv')

In [44]:
merged = results[['raceId', 'driverId', 'constructorId','positionOrder']].merge(races[['raceId','year']], on='raceId',how='left')

In [45]:
merged = merged.merge(drivers[['driverId','forename','surname']],on='driverId', how='left')

In [46]:
merged = merged.merge(constructors[['constructorId', 'name']], on='constructorId', how='left')

In [58]:
merged = merged.merge(driver_standings[['raceId','driverId','points']], on=['raceId','driverId'], how='left')

In [59]:
merged['driver_name'] = merged['forename'] + ' ' + merged['surname']

In [60]:
merged.head()

,raceId,driverId,constructorId,positionOrder,year,forename,surname,name,driver_name,points
0,18,1,1,1,2008,Lewis,Hamilton,McLaren,Lewis Hamilton,10.0
1,18,2,2,2,2008,Nick,Heidfeld,BMW Sauber,Nick Heidfeld,8.0
2,18,3,3,3,2008,Nico,Rosberg,Williams,Nico Rosberg,6.0
3,18,4,4,4,2008,Fernando,Alonso,Renault,Fernando Alonso,5.0
4,18,5,1,5,2008,Heikki,Kovalainen,McLaren,Heikki Kovalainen,4.0

In [61]:
merged_red_bull = merged.loc[(merged['name'] == 'Red Bull') & (merged['year'].between(2021,2024))]

In [65]:
avg_position = merged_red_bull.groupby(['year','driver_name']).agg(avg_position=('positionOrder', 'mean'), points=('points','max')).reset_index()

In [67]:
avg_position.sort_values(['year','avg_position'], ascending=[False, True])

   year     driver_name  avg_position  points
6  2024  Max Verstappen      3.625000   437.0
7  2024    Sergio Pérez      9.625000   152.0
4  2023  Max Verstappen      1.272727   575.0
5  2023    Sergio Pérez      5.863636   285.0
2  2022  Max Verstappen      3.500000   454.0
3  2022    Sergio Pérez      5.409091   305.0
0  2021  Max Verstappen      4.136364   395.5
1  2021    Sergio Pérez      7.545455   190.0

In [69]:
max_data = avg_position.loc[avg_position['driver_name'] == 'Max Verstappen']

In [70]:
perez_data = avg_position.loc[avg_position['driver_name'] == 'Sergio Pérez']

In [77]:
combined_data = max_data.merge(perez_data, on='year', how='left')

In [78]:
combined_data = combined_data.rename(columns={'driver_name_x':'driver_1', 'avg_position_x':'avg_pos_driver_1', 'points_x':'points_driver_1'})

In [80]:
combined_data = combined_data.rename(columns={'driver_name_y':'driver_2', 'avg_position_y':'avg_pos_driver_2', 'points_y':'points_driver_2'})

In [81]:
combined_data

,year,driver_1,avg_pos_driver_1,points_driver_1,driver_2,avg_pos_driver_2,points_driver_2
0,2021,Max Verstappen,4.136364,395.5,Sergio Pérez,7.545455,190.0
1,2022,Max Verstappen,3.500000,454.0,Sergio Pérez,5.409091,305.0
2,2023,Max Verstappen,1.272727,575.0,Sergio Pérez,5.863636,285.0
3,2024,Max Verstappen,3.625000,437.0,Sergio Pérez,9.625000,152.0

In [82]:
combined_data['points_gap'] = combined_data['points_driver_1'] - combined_data['points_driver_2']

In [85]:
combined_data['position_gap'] = combined_data['avg_pos_driver_2'] - combined_data['avg_pos_driver_1']

In [86]:
combined_data

,year,driver_1,avg_pos_driver_1,points_driver_1,driver_2,avg_pos_driver_2,points_driver_2,points_gap,position_gap
0,2021,Max Verstappen,4.136364,395.5,Sergio Pérez,7.545455,190.0,205.5,3.409091
1,2022,Max Verstappen,3.500000,454.0,Sergio Pérez,5.409091,305.0,149.0,1.909091
2,2023,Max Verstappen,1.272727,575.0,Sergio Pérez,5.863636,285.0,290.0,4.590909
3,2024,Max Verstappen,3.625000,437.0,Sergio Pérez,9.625000,152.0,285.0,6.000000

In [87]:
combined_data = combined_data.round(2)

In [88]:
combined_data

,year,driver_1,avg_pos_driver_1,points_driver_1,driver_2,avg_pos_driver_2,points_driver_2,points_gap,position_gap
0,2021,Max Verstappen,4.14,395.5,Sergio Pérez,7.55,190.0,205.5,3.41
1,2022,Max Verstappen,3.50,454.0,Sergio Pérez,5.41,305.0,149.0,1.91
2,2023,Max Verstappen,1.27,575.0,Sergio Pérez,5.86,285.0,290.0,4.59
3,2024,Max Verstappen,3.62,437.0,Sergio Pérez,9.62,152.0,285.0,6.00